<?php

function flair_init() {
  $json = file_get_contents('http://www.reddit.com/r/gif.json');
  $gif_array = array();
  $gif_obj = json_decode($json)->data->children;  
  foreach($gif_obj as $obj) {
    $gif_url = $obj->data->url;
    $pathinfo = pathinfo($gif_url);
    if (strtolower(@$pathinfo['extension']) == 'gif') {
      $gif_array[] = $gif_url;
    }
  }
  drupal_add_js(array('flair' => $gif_array), 'setting');
  drupal_add_js(drupal_get_path('module', 'flair') . '/js/app.js');
}